

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

volumes:
  postgres_volume:

# celery




