# Generated by Django 5.1.1 on 2024-10-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history", old_name="ip_adress", new_name="ip_address",
        ),
    ]
