# Generated by Django 5.1.1 on 2024-10-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history_app", "0002_rename_ip_adress_history_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="history", name="his", field=models.BooleanField(default=False),
        ),
    ]
