# Generated by Django 5.1.1 on 2024-10-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history_app", "0003_history_his"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="his",),
        migrations.AddField(
            model_name="history",
            name="rec_to_history",
            field=models.BooleanField(default=True),
        ),
    ]
