# Generated by Django 5.1.1 on 2024-12-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0004_remove_history_his_history_rec_to_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
