# Generated by Django 5.1.1 on 2024-12-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0005_history_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user_i',
        ),
    ]
