# Generated by Django 5.1.1 on 2024-12-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0006_rename_user_id_history_user_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_i',
        ),
    ]
