# Generated by Django 5.1.1 on 2024-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0007_remove_history_user_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
