# Generated by Django 5.1.1 on 2024-12-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0008_history_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
